@baseUrl = {{$dotenv BASE_URL}}

###
# @name createSupplierGroup
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/examples HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}

###
# @name createManySupplierGroup
# @prompt name1
# @prompt phone1
# @prompt name2
# @prompt phone2
POST {{baseUrl}}/v1/examples/create-many HTTP/1.1
Accept: application/json
Content-Type: application/json

[
  {
    "name": "{{name1}}",
    "phone": "{{phone1}}"  
  },
  {
    "name": "{{name2}}",
    "phone": "{{phone2}}"  
  }
]

###
# @name retrieveAllSupplierGroup
GET {{baseUrl}}/v1/examples HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name retrieveSupplierGroup
# @prompt id
GET {{baseUrl}}/v1/examples/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name updateSupplierGroup
# @prompt id
# @prompt name
# @prompt phone
PATCH {{baseUrl}}/v1/examples/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}

###
# @name updateManySupplierGroup
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/examples/update-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "filter": {
    "name": "{{name}}"
  },
  "data": {
    "phone": "{{phone}}"
  }
}

###
# @name deleteSupplierGroup
# @prompt id
DELETE {{baseUrl}}/v1/examples/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name deleteManySupplierGroup
# @prompt id1
# @prompt id2
POST {{baseUrl}}/v1/examples/delete-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "ids": ["{{id1}}","{{id2}}"]
}

###
# @name createTransactionSupplierGroup
# @prompt name1
# @prompt phone1
# @prompt name2
# @prompt phone2
POST {{baseUrl}}/v1/examples/transaction HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "data1": {
    "name": "{{name1}}",
    "phone": "{{phone1}}"  
  },
  "data2": {
    "name": "{{name2}}",
    "phone": "{{phone2}}"  
  }
}