export const seeds = [
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'CASH',
    type_alias: 'KAS',
    number: 10101,
    name: 'CASH',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'CASH-BANK TRANSFER',
    type_alias: 'AYAT SILANG KAS BANK',
    number: 10199,
    name: 'CASH BANK TRANSFER',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'BANK',
    type_alias: 'BANK',
    number: 10201,
    name: 'BANK',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'SUPPLIES',
    type_alias: 'PERLENGKAPAN',
    number: 10301,
    name: 'SUPPLIES',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'INVENTORY',
    type_alias: 'PERSEDIAAN',
    number: 10401,
    name: 'RAW MATERIAL INVENTORY',
    increasing_in: 'DEBIT',
    subledger: 'ITEM',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'INVENTORY',
    type_alias: 'PERSEDIAAN',
    number: 10402,
    name: 'INDIRECT MATERIAL INVENTORY',
    increasing_in: 'DEBIT',
    subledger: 'ITEM',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'INVENTORY',
    type_alias: 'PERSEDIAAN',
    number: 10403,
    name: 'WORK IN PROCESS INVENTORY',
    increasing_in: 'DEBIT',
    subledger: 'ITEM',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'INVENTORY',
    type_alias: 'PERSEDIAAN',
    number: 10404,
    name: 'FINISHED GOOD INVENTORY',
    increasing_in: 'DEBIT',
    subledger: 'ITEM',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'INVENTORY',
    type_alias: 'PERSEDIAAN',
    number: 10405,
    name: 'INVENTORY IN DISTRIBUTION',
    increasing_in: 'DEBIT',
    subledger: 'ITEM',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'NOTE RECEIVABLE',
    type_alias: 'WESEL TAGIH',
    number: 10501,
    name: 'NOTE RECEIVABLE',
    increasing_in: 'DEBIT',
    subledger: 'CUSTOMER',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'ACCOUNT RECEIVABLE',
    type_alias: 'PIUTANG USAHA',
    number: 10502,
    name: 'ACCOUNT RECEIVABLE',
    increasing_in: 'DEBIT',
    subledger: 'CUSTOMER',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'ACCOUNT RECEIVABLE OF MANAGEMENT',
    type_alias: 'PIUTANG MANAJEMEN',
    number: 10503,
    name: 'ACCOUNT RECEIVABLE OF MANAGEMENT',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'ACCOUNT RECEIVABLE OF EMPLOYEE',
    type_alias: 'PIUTANG KARYAWAN',
    number: 10504,
    name: 'ACCOUNT RECEIVABLE OF EMPLOYEE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'OTHER ACCOUNT RECEIVABLE',
    type_alias: 'PIUTANG LAIN',
    number: 10599,
    name: 'OTHER ACCOUNT RECEIVABLE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'PURCHASE DOWNPAYMENT',
    type_alias: 'UANG MUKA PEMBELIAN',
    number: 10601,
    name: 'PURCHASE DOWN PAYMENT',
    increasing_in: 'DEBIT',
    subledger: 'SUPPLIER',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'PURCHASE DOWNPAYMENT',
    type_alias: 'UANG MUKA EKSPEDISI',
    number: 10602,
    name: 'EXPEDITION DOWN PAYMENT',
    increasing_in: 'DEBIT',
    subledger: 'EXPEDITION',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'ASSET DOWN PAYMENT ',
    type_alias: 'UANG MUKA ASSET',
    number: 10603,
    name: 'FIX ASSET DOWN PAYMENT ',
    increasing_in: 'DEBIT ',
    subledger: 'SUPPLIER ',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'INCOME TAX RECEIVABLE',
    type_alias: 'PPN MASUKAN',
    number: 10701,
    name: 'INCOME TAX RECEIVABLE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'OTHER CURRENT ASSET',
    type_alias: 'ASET LANCAR LAIN-LAIN',
    number: 10801,
    name: 'MARKETABLE SECURITIES',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'OTHER CURRENT ASSET',
    type_alias: 'ASET LANCAR LAIN-LAIN',
    number: 10901,
    name: 'PREPAID ADVERTISING',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'OTHER CURRENT ASSET',
    type_alias: 'ASET LANCAR LAIN-LAIN',
    number: 10902,
    name: 'PREPAID RENT',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'OTHER CURRENT ASSET',
    type_alias: 'ASET LANCAR LAIN-LAIN',
    number: 10903,
    name: 'PREPAID INSURANCE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET',
    type_alias: 'ASET TETAP',
    number: 11101,
    name: 'LAND',
    increasing_in: 'DEBIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET',
    type_alias: 'ASET TETAP',
    number: 11202,
    name: 'FACTORY BUILDING',
    increasing_in: 'DEBIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET DEPRECIATION',
    type_alias: 'DEPRESIASI ASET TETAP',
    number: 11203,
    name: 'ACCUMULATED DEPRECIATION OF FACTORY BUILDING',
    increasing_in: 'CREDIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET',
    type_alias: 'ASET TETAP',
    number: 11301,
    name: 'OFFICE BUILDING',
    increasing_in: 'DEBIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET DEPRECIATION',
    type_alias: 'DEPRESIASI ASET TETAP',
    number: 11302,
    name: 'ACCUMULATED DEPRECIATION OF OFFICE BUILDING',
    increasing_in: 'CREDIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET',
    type_alias: 'ASET TETAP',
    number: 11401,
    name: 'MACHINE',
    increasing_in: 'DEBIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET DEPRECIATION',
    type_alias: 'DEPRESIASI ASET TETAP',
    number: 11402,
    name: 'ACCUMULATED DEPRECIATION OF MACHINE',
    increasing_in: 'CREDIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET',
    type_alias: 'ASET TETAP',
    number: 11501,
    name: 'EQUIPMENT',
    increasing_in: 'DEBIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET DEPRECIATION',
    type_alias: 'DEPRESIASI ASET TETAP',
    number: 11502,
    name: 'ACCUMULATED DEPRECITION OF EQUIPMENT',
    increasing_in: 'CREDIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET',
    type_alias: 'ASET TETAP',
    number: 11601,
    name: 'FACTORY VEHICLE',
    increasing_in: 'DEBIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET DEPRECIATION',
    type_alias: 'DEPRESIASI ASET TETAP',
    number: 11602,
    name: 'ACCUMULATED DEPRECIATION OF FACTORY VEHICLE',
    increasing_in: 'CREDIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET',
    type_alias: 'ASET TETAP',
    number: 11701,
    name: 'OFFICE VEHICLE',
    increasing_in: 'DEBIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'FIX ASSET DEPRECIATION',
    type_alias: 'DEPRESIASI ASET TETAP',
    number: 11702,
    name: 'ACCUMULATED DEPRECIATION OF OFFICE VEHICLE',
    increasing_in: 'CREDIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'OTHER ASSETS',
    type_alias: 'ASET TETAP',
    number: 11801,
    name: 'INTANGIBLE FIX ASSETS',
    increasing_in: 'DEBIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'ASSET',
    category: 'OTHER ASSETS AMORTIZATION',
    type_alias: 'AMORTISASI ASET TETAP',
    number: 11802,
    name: 'ACCUMULATED AMORTIZED OF INTANGBLE FIX ASSETS',
    increasing_in: 'CREDIT',
    subledger: 'FIXED ASSET',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'NOTE PAYABLE',
    type_alias: 'WESEL BAYAR',
    number: 20101,
    name: 'NOTE PAYABLE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'ACCOUNT PAYABLE',
    type_alias: 'HUTANG USAHA',
    number: 20201,
    name: 'ACCOUNT PAYABLE',
    increasing_in: 'CREDIT',
    subledger: 'SUPPLIER',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'SALES DOWNPAYMENT',
    type_alias: 'UANG MUKA PENJUALAN',
    number: 20301,
    name: 'SALES DOWN PAYMENT',
    increasing_in: 'CREDIT',
    subledger: 'CUSTOMER',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'ASSET DOWN PAYMENT ',
    type_alias: 'UANG MUKA PENJUALAN ASSET',
    number: 20302,
    name: 'ASSET SALES DOWN PAYMENT ',
    increasing_in: 'CREDIT',
    subledger: 'CUSTOMER',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'INCOME TAX PAYABLE',
    type_alias: 'PPN KELUARAN',
    number: 20401,
    name: 'INCOME TAX PAYABLE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'OTHER CURRENT LIABILITY',
    type_alias: 'LIABILITAS JANGKA PENDEK LAIN-LAIN',
    number: 20501,
    name: 'ACCOUNT PAYABLE EXPEDITION',
    increasing_in: 'CREDIT',
    subledger: 'EXPEDITION',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'OTHER CURRENT LIABILITY',
    type_alias: 'LIABILITAS JANGKA PENDEK LAIN-LAIN',
    number: 20502,
    name: 'SALARY PAYABLE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'OTHER CURRENT LIABILITY',
    type_alias: 'LIABILITAS JANGKA PENDEK LAIN - LAIN ',
    number: 20503,
    name: 'ACCOUNT PAYABLE FIX ASSET',
    increasing_in: 'CREDIT',
    subledger: 'SUPPLIER ',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'OTHER CURRENT LIABILITY',
    type_alias: 'LIABILITAS JANGKA PENDEK LAIN-LAIN',
    number: 20602,
    name: 'INTEREST PAYABLE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'OTHER CURRENT LIABILITY',
    type_alias: 'LIABILITAS JANGKA PENDEK LAIN-LAIN',
    number: 20701,
    name: 'OTHER CURRENT PAYABLE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'LONG TERM LIABILITY',
    type_alias: 'LIABILITAS JANGKA PANJANG ',
    number: 21101,
    name: 'BANK PAYABLE <BANK_NAME>',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'LONG TERM LIABILITY',
    type_alias: 'LIABILITAS JANGKA PANJANG ',
    number: 21201,
    name: 'HYPOTIC PAYABLE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'LONG TERM LIABILITY',
    type_alias: 'LIABILITAS JANGKA PANJANG ',
    number: 21301,
    name: 'BOND PAYABLE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'LIABILITY ',
    category: 'LONG TERM LIABILITY',
    type_alias: 'LIABILITAS JANGKA PANJANG ',
    number: 21401,
    name: 'OTHER LONG TERM PAYABLE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'EQUITY ',
    category: 'OWNER EQUITY',
    type_alias: 'MODAL PEMILIK',
    number: 30101,
    name: 'STOCK CAPITAL',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'EQUITY ',
    category: 'SHAREHOLER DISTRIBUTION',
    type_alias: 'DISTRIBUSI PEMEGANG SAHAM',
    number: 30102,
    name: 'DIVIDEND',
    increasing_in: 'DEBIT ',
  },
  {
    created_date: new Date(),
    type: 'EQUITY ',
    category: 'RETAINED EARNING',
    type_alias: 'LABA DITAHAN',
    number: 30103,
    name: 'RETAINED EARNING',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'EQUITY ',
    category: 'NET INCOME FOR THE MONTH ',
    type_alias: 'NET INCOME FOR THE MONTH ',
    number: 30111,
    name: 'NET INCOME FOR THE MONTH',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'EQUITY ',
    category: 'NET INCOME FOR THE YEAR ',
    type_alias: 'NET INCOME FOR THE YEAR ',
    number: 30112,
    name: 'NET INCOME FOR THE YEAR',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'SALES INCOME',
    type_alias: 'PENDAPATAN PENJUALAN',
    number: 40101,
    name: 'SALES',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'SALES INCOME',
    type_alias: 'PENDAPATAN PENJUALAN',
    number: 40102,
    name: 'SALES RETURN',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'SALES INCOME',
    type_alias: 'PENDAPATAN PENJUALAN',
    number: 40103,
    name: 'SALES DISCOUNT',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'OTHER INCOME',
    type_alias: 'PENDAPATAN LAIN ',
    number: 41101,
    name: 'FULLFILLMENT',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'OTHER INCOME',
    type_alias: 'PENDAPATAN LAIN-LAIN',
    number: 41102,
    name: 'INTEREST INCOME',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'OTHER INCOME',
    type_alias: 'PENDAPATAN LAIN-LAIN',
    number: 41103,
    name: 'EXCHANGE RATE',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'OTHER INCOME',
    type_alias: 'PENDAPATAN LAIN-LAIN',
    number: 41199,
    name: 'OTHER INCOME',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'OTHER INCOME',
    type_alias: 'PENDAPATAN LAIN-LAIN',
    number: 41200,
    name: 'NON OPERATING INCOME',
    increasing_in: 'CREDIT',
  },
  {
    created_date: new Date(),
    type: 'INCOME ',
    category: 'COST OF SALES',
    type_alias: 'BEBAN POKOK PENJUALAN',
    number: 50101,
    name: 'COST OF SALES',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'PURCHASE DISCOUNT ',
    type_alias: 'POTONGAN PEMBELIAN ',
    number: 50102,
    name: 'PURCHASE DISCOUNT ',
    increasing_in: 'DEBIT ',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50111,
    name: 'DELIVERY EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50112,
    name: 'DIFFERENCE STOCK EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50113,
    name: 'SALARY EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50114,
    name: 'OFFICE ELECTRICITY EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50115,
    name: 'OFFICE WATER EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50116,
    name: 'OFFICE CATERING EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50117,
    name: 'MAINTENANCE OF OFFICE EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50118,
    name: 'OFFICE BUILDING DEPRECIATION EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50119,
    name: 'EQUIPMENT DEPRECIATION EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50120,
    name: 'OFFICE VEHICLE DEPRECIATION EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50121,
    name: 'AMORTIZATION INTANGIBLE FIX ASSETS EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50122,
    name: 'SUPPLIES EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50123,
    name: 'RENT EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50124,
    name: 'INSURANCE  EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50125,
    name: 'TELEPHONE EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50126,
    name: 'INTERNET EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50127,
    name: 'CONSULTANT SERVICE EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50128,
    name: 'BANK ADMINISTRATION EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50129,
    name: 'INTEREST EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50130,
    name: 'TAX EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50131,
    name: 'OTHER EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50132,
    name: 'ACCOMODATION EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'OFFICE',
    number: 50133,
    name: 'OFFICE GASOLINE EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'OTHER EXPENSE',
    type_alias: 'BEBAN NON OPERASIONAL',
    group: 'OFFICE',
    number: 50134,
    name: 'NON OPERATING EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'MARKETING',
    number: 50135,
    name: 'ENTERTAIMENT EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'MARKETING',
    number: 50136,
    name: 'ADVERTISING EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'DIRECT EXPENSE',
    type_alias: 'BEBAN OPERASIONAL',
    group: 'MARKETING',
    number: 50137,
    name: 'SALES COMMISSION EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50138,
    name: 'WAGE EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50139,
    name: 'FACTORY GASOLINE EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50140,
    name: 'FACTORY ELECTRICITY EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50141,
    name: 'FACTORY WATER EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50142,
    name: 'FACTORY CATERING EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50143,
    name: 'MAINTENANCE OF FACTORY EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50144,
    name: 'FACTORY BUILDING DEPRECIATION EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50145,
    name: 'MACHINE DEPRECIATION EXPENSE',
    increasing_in: 'DEBIT',
  },
  {
    created_date: new Date(),
    type: 'EXPENSE ',
    category: 'FACTORY OVERHEAD COST',
    type_alias: 'BIAYA OVERHEAD PABRIK',
    group: 'FACTORY',
    number: 50146,
    name: 'FACTORY VEHICLE DEPRECIATION EXPENSE',
    increasing_in: 'DEBIT',
  },
]
