export const seeds = [
  [
    {
      group: 'master',
      feature: 'users',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'roles',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'branches',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'warehouses',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'allocation groups',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'allocations',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'supplier groups',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'suppliers',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'customer groups',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'customers',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'item categories',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
    {
      group: 'master',
      feature: 'customers',
      create: false,
      read: false,
      edit: false,
      delete: false,
    },
  ],
]
