@baseUrl = {{$dotenv BASE_URL}}

###
# @name createChartOfAccount
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/accounting/chart-of-accounts HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}

###
# @name createManyChartOfAccount
# @prompt name1
# @prompt phone1
# @prompt name2
# @prompt phone2
POST {{baseUrl}}/v1/accounting/chart-of-accounts/create-many HTTP/1.1
Accept: application/json
Content-Type: application/json

[
  {
    "name": "{{name1}}",
    "phone": "{{phone1}}"  
  },
  {
    "name": "{{name2}}",
    "phone": "{{phone2}}"  
  }
]

###
# @name retrieveAllChartOfAccount
GET {{baseUrl}}/v1/accounting/chart-of-accounts HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name retrieveAllChartOfAccount2
GET {{baseUrl}}/v1/accounting/chart-of-accounts HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "page": 2
}

###
# @name retrieveChartOfAccount
# @prompt id
GET {{baseUrl}}/v1/accounting/chart-of-accounts/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name updateChartOfAccount
# @prompt id
# @prompt name
# @prompt phone
PATCH {{baseUrl}}/v1/accounting/chart-of-accounts/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{name}}",
  "phone": "{{phone}}"
}

###
# @name updateManyChartOfAccount
# @prompt name
# @prompt phone
POST {{baseUrl}}/v1/accounting/chart-of-accounts/update-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "filter": {
    "name": "{{name}}"
  },
  "data": {
    "phone": "{{phone}}"
  }
}

###
# @name deleteChartOfAccount
# @prompt id
DELETE {{baseUrl}}/v1/accounting/chart-of-accounts/{{id}} HTTP/1.1
Accept: application/json
Content-Type: application/json

###
# @name deleteManyChartOfAccount
# @prompt id1
# @prompt id2
POST {{baseUrl}}/v1/accounting/chart-of-accounts/delete-many HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "ids": ["{{id1}}","{{id2}}"]
}

###
# @name createTransactionChartOfAccount
# @prompt name1
# @prompt phone1
# @prompt name2
# @prompt phone2
POST {{baseUrl}}/v1/accounting/chart-of-accounts/transaction HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "data1": {
    "name": "{{name1}}",
    "phone": "{{phone1}}"  
  },
  "data2": {
    "name": "{{name2}}",
    "phone": "{{phone2}}"  
  }
}