import { type IDatabase } from '@point-hub/papi'

import { CreateChartOfAccountCategoryRepository } from '@/modules/master/chart-of-account-categories/repositories/create.repository'
import { CreateChartOfAccountTypeRepository } from '@/modules/master/chart-of-account-types/repositories/create.repository'
import { CreateChartOfAccountRepository } from '@/modules/master/chart-of-accounts/repositories/create.repository'
import { toTitleCase } from '@/utils/titlecase'

export interface ISeed {
  type?: string
  category?: string
  group?: string
  number?: string
  name?: string
  subledger?: string
}

export const seed = async (dbConnection: IDatabase, options: unknown) => {
  console.info(`[seed] chart of accounts data`)
  // delete all data inside collection
  await dbConnection.collection('chart_of_accounts').deleteAll(options)
  await dbConnection.collection('chart_of_account_categories').deleteAll(options)
  await dbConnection.collection('chart_of_account_types').deleteAll(options)
  // prepare repository
  const createChartOfAccountTypeRepository = new CreateChartOfAccountTypeRepository(dbConnection)
  const createChartOfAccountCategoryRepository = new CreateChartOfAccountCategoryRepository(dbConnection)
  const createChartOfAccountRepository = new CreateChartOfAccountRepository(dbConnection)
  // insert new seeder data
  const uniqueTypes = [...new Map(seeds.map((el) => [el.type, el])).values()]
  const types = uniqueTypes.map((el) => el.type)
  for (const type of types) {
    // insert account type
    const typeResponse = await createChartOfAccountTypeRepository.handle({ name: toTitleCase(type) }, options)
    const filteredCategorySeeds = seeds.filter((el) => el.type === type)
    const uniqueCategories = [...new Map(filteredCategorySeeds.map((el) => [el.category, el])).values()]
    const categories = uniqueCategories.map((el) => el.category)
    for (const category of categories) {
      // insert account category
      const categoryResponse = await createChartOfAccountCategoryRepository.handle(
        {
          type_id: typeResponse.inserted_id,
          name: toTitleCase(category),
        },
        options,
      )
      const filteredAccountSeeds = seeds.filter((el) => el.category === category)
      const accounts = filteredAccountSeeds.filter((el) => el.category === category)
      for (const account of accounts) {
        // insert account
        await createChartOfAccountRepository.handle(
          {
            category_id: categoryResponse.inserted_id,
            number: account.number,
            name: toTitleCase(account.name),
            subledger: toTitleCase(account.subledger),
          },
          options,
        )
      }
    }
  }
}

export const seeds = [
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'cash',
    category: 'kas',
    number: '10101',
    name: 'kas besar',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'cash',
    category: 'kas',
    number: '10199',
    name: 'ayat silang kas / bank',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'bank',
    category: 'bank',
    number: '10201',
    name: 'bank',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'supplies',
    category: 'peralatan',
    number: '10301',
    name: 'peralatan',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10401',
    name: 'persediaan bahan baku',
    subledger: 'item',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10402',
    name: 'persediaan bahan setengah jadi',
    subledger: 'item',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10403',
    name: 'persediaan bahan dalam proses',
    subledger: 'item',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10404',
    name: 'persediaan barang jadi',
    subledger: 'item',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10405',
    name: 'persediaan dalam perjalanan',
    subledger: 'item',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'note receivable',
    category: 'wesel tagih',
    number: '10501',
    name: 'wesel tagih',
    subledger: 'customer',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'account receivable',
    category: 'piutang usaha',
    number: '10502',
    name: 'piutang usaha',
    subledger: 'customer',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'account receivable of management',
    category: 'piutang direksi',
    number: '10503',
    name: 'piutang direksi',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'account receivable of employee',
    category: 'piutang karyawan',
    number: '10504',
    name: 'piutang karyawan',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other account receivable',
    category: 'piutang lainnya',
    number: '10599',
    name: 'piutang lainnya',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'down payment for purchase',
    category: 'uang muka pembelian',
    number: '10601',
    name: 'uang muka pembelian',
    subledger: 'supplier',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'down payment for expedition',
    category: 'uang muka pembelian',
    number: '10602',
    name: 'uang muka ekspedisi',
    subledger: 'expedition',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'down payment for fixed asset',
    category: 'uang muka aset tetap',
    number: '10603',
    name: 'uang muka aset tetap',
    subledger: 'supplier',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'income tax receivable',
    category: 'ppn masukan',
    number: '10701',
    name: 'ppn masukan',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other current asset',
    category: 'aset lancar lainnya',
    number: '10801',
    name: 'surat berharga',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other current asset',
    category: 'aset lancar lainnya',
    number: '10901',
    name: 'iklan dibayar dimuka',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other current asset',
    category: 'aset lancar lainnya',
    number: '10902',
    name: 'sewa dibayar dimuka',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other current asset',
    category: 'aset lancar lainnya',
    number: '10903',
    name: 'asuransi dibayar dimuka',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11101',
    name: 'tanah',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11202',
    name: 'bangunan pabrik',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11203',
    name: 'akumulasi penyusutan bangunan pabrik',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11301',
    name: 'bangunan kantor',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11302',
    name: 'akumulasi penyusutan bangunan kantor',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11401',
    name: 'mesin',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11402',
    name: 'akumulasi penyusutan mesin',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11501',
    name: 'peralatan',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11502',
    name: 'akumulasi penyusutan peralatan',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11601',
    name: 'kendaraan pabrik',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11602',
    name: 'akumulasi penyusutan kendaraan pabrik',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11701',
    name: 'kendaraan kantor',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11702',
    name: 'akumulasi penyusutan office vehicle',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other assets',
    category: 'aset lainnya',
    number: '11801',
    name: 'aset tidak berwujud',
    subledger: 'fixed asset',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other assets amortization',
    category: 'amortisasi aset lainnya',
    number: '11802',
    name: 'akumulasi amortisasi aset tidak berwujud',
    subledger: 'fixed asset',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'note payable',
    category: 'wesel bayar',
    number: '20101',
    name: 'wesel bayar',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'account payable',
    category: 'hutang usaha',
    number: '20201',
    name: 'hutang usaha',
    subledger: 'supplier',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'sales down payment',
    category: 'uang muka penjualan',
    number: '20301',
    name: 'uang muka penjualan',
    subledger: 'customer',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'asset sales down payment',
    category: 'uang muka penjualan aset tetap',
    number: '20302',
    name: 'asset sales down payment',
    subledger: 'customer',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'income tax payable',
    category: 'ppn keluaran',
    number: '20401',
    name: 'ppn keluaran',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'other current liability',
    category: 'kewajiban lainnya',
    number: '20501',
    name: 'hutang ekspedisi',
    subledger: 'expedition',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'other current liability',
    category: 'kewajiban lainnya',
    number: '20503',
    name: 'hutang aset tetap',
    subledger: 'supplier',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'other current liability',
    category: 'kewajiban lainnya',
    number: '20602',
    name: 'hutang bunga',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'other current liability',
    category: 'kewajiban lainnya',
    number: '20701',
    name: 'hutang lainnya',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'long term liability',
    category: 'hutang jangka panjang',
    number: '21101',
    name: 'hutang bank',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'long term liability',
    category: 'hutang jangka panjang',
    number: '21201',
    name: 'hutang hipotik',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'long term liability',
    category: 'hutang jangka panjang',
    number: '21301',
    name: 'hutang obligasi',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'long term liability',
    category: 'hutang jangka panjang',
    number: '21401',
    name: 'hutang jangka panjang lainnya',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'owner equity',
    category: 'modal pemilik',
    number: '30101',
    name: 'stock capital',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'dividend',
    category: 'dividen',
    number: '30102',
    name: 'dividen',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'retained earning',
    category: 'laba ditahan',
    number: '30103',
    name: 'laba ditahan',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'net income for the month',
    category: 'laba rugi s/d bulan lalu',
    number: '30111',
    name: 'laba rugi s/d bulan lalu',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'net income for the year',
    category: 'laba rugi s/d tahun lalu',
    number: '30112',
    name: 'laba rugi s/d tahun lalu',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'net income for the year',
    category: 'laba rugi bulan berjalan',
    number: '30113',
    name: 'laba rugi bulan berjalan',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'sales income',
    category: 'pendapatan',
    number: '40101',
    name: 'penjualan',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'sales income',
    category: 'pendapatan',
    number: '40102',
    name: 'retur penjualan',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'sales income',
    category: 'pendapatan',
    number: '40103',
    name: 'potongan penjualan',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'other income',
    category: 'pendapatan lainnya',
    number: '41101',
    name: 'income (expense) payment difference',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'other income',
    category: 'pendapatan lainnya',
    number: '41102',
    name: 'interest income',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'other income',
    category: 'pendapatan lainnya',
    number: '41103',
    name: 'exchange rate',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'other income',
    category: 'pendapatan lainnya',
    number: '41199',
    name: 'other income',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'other income',
    category: 'pendapatan lainnya',
    number: '41200',
    name: 'non operating income',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category: 'cost of sales',
    number: '50101',
    name: 'cost of sales',
  },
  {
    type: 'expense',
    category: 'purchase discount',
    number: '50102',
    name: 'purchase discount',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50111',
    name: 'delivery expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50112',
    name: 'difference stock expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50113',
    name: 'salary expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50114',
    name: 'office electricity expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50115',
    name: 'office water expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50116',
    name: 'office catering expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50117',
    name: 'maintenance of office expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50118',
    name: 'office building depreciation expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50119',
    name: 'equipment depreciation expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50120',
    name: 'office vehicle depreciation expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50121',
    name: 'amortization intangible fixed assets expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50122',
    name: 'supplies expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50123',
    name: 'rent expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50124',
    name: 'insurance  expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50125',
    name: 'telephone expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50126',
    name: 'internet expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50127',
    name: 'consultant service expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50128',
    name: 'bank administration expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50129',
    name: 'interest expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50130',
    name: 'tax expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50131',
    name: 'other expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50132',
    name: 'accomodation expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'office',
    number: '50133',
    name: 'office gasoline expense',
  },
  {
    type: 'expense',
    category: 'other expense',
    group: 'office',
    number: '50134',
    name: 'non operating expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'marketing',
    number: '50135',
    name: 'entertaiment expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'marketing',
    number: '50136',
    name: 'advertising expense',
  },
  {
    type: 'expense',
    category: 'direct expense',
    group: 'marketing',
    number: '50137',
    name: 'sales commission expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50138',
    name: 'wage expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50139',
    name: 'factory gasoline expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50140',
    name: 'factory electricity expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50141',
    name: 'factory water expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50142',
    name: 'factory catering expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50143',
    name: 'maintenance of factory expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50144',
    name: 'factory building depreciation expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50145',
    name: 'machine depreciation expense',
  },
  {
    type: 'expense',
    category: 'factory overhead cost',
    group: 'factory',
    number: '50146',
    name: 'factory vehicle depreciation expense',
  },
]
