import { type IDatabase } from '@point-hub/papi'

import { CreateChartOfAccountCategoryRepository } from '@/modules/master/chart-of-account-categories/repositories/create.repository'
import { CreateChartOfAccountTypeRepository } from '@/modules/master/chart-of-account-types/repositories/create.repository'
import { CreateChartOfAccountRepository } from '@/modules/master/chart-of-accounts/repositories/create.repository'
import { toTitleCase } from '@/utils/titlecase'

export interface ISeed {
  type?: string
  category?: string
  group?: string
  number?: string
  name?: string
  subledger?: string
}

export const seed = async (dbConnection: IDatabase, options: unknown) => {
  console.info(`[seed] chart of accounts data`)
  // delete all data inside collection
  await dbConnection.collection('chart_of_accounts').deleteAll(options)
  await dbConnection.collection('chart_of_account_categories').deleteAll(options)
  await dbConnection.collection('chart_of_account_types').deleteAll(options)
  // prepare repository
  const createChartOfAccountTypeRepository = new CreateChartOfAccountTypeRepository(dbConnection)
  const createChartOfAccountCategoryRepository = new CreateChartOfAccountCategoryRepository(dbConnection)
  const createChartOfAccountRepository = new CreateChartOfAccountRepository(dbConnection)
  // insert new seeder data
  const uniqueTypes = [...new Map(seeds.map((el) => [el.type, el])).values()]
  for (const type of uniqueTypes) {
    // insert account type
    const typeResponse = await createChartOfAccountTypeRepository.handle(
      { code: toTitleCase(type.type_code), name: toTitleCase(type.type) },
      options,
    )
    const filteredCategorySeeds = seeds.filter((el) => el.type_code === type.type_code)
    const uniqueCategories = [...new Map(filteredCategorySeeds.map((el) => [el.category, el])).values()]
    for (const category of uniqueCategories) {
      // insert account category
      const categoryResponse = await createChartOfAccountCategoryRepository.handle(
        {
          type_id: typeResponse.inserted_id,
          code: toTitleCase(category.category_code),
          name: toTitleCase(category.category),
        },
        options,
      )
      const accounts = seeds.filter((el) => el.category_code === category.category_code)
      for (const account of accounts) {
        // insert account
        await createChartOfAccountRepository.handle(
          {
            category_id: categoryResponse.inserted_id,
            number: account.number,
            name: toTitleCase(account.name),
            subledger: toTitleCase(account.subledger),
          },
          options,
        )
      }
    }
  }
}

export const seeds = [
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'cash',
    category: 'kas',
    number: '10101',
    name: 'kas besar',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'cash',
    category: 'kas',
    number: '10199',
    name: 'ayat silang kas / bank',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'bank',
    category: 'bank',
    number: '10201',
    name: 'bank',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'supplies',
    category: 'peralatan',
    number: '10301',
    name: 'peralatan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10401',
    name: 'persediaan bahan baku',
    subledger: 'item',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10402',
    name: 'persediaan bahan setengah jadi',
    subledger: 'item',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10403',
    name: 'persediaan bahan dalam proses',
    subledger: 'item',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10404',
    name: 'persediaan barang jadi',
    subledger: 'item',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'inventory',
    category: 'persediaan',
    number: '10405',
    name: 'persediaan dalam perjalanan',
    subledger: 'item',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'note receivable',
    category: 'wesel tagih',
    number: '10501',
    name: 'wesel tagih',
    subledger: 'customer',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'account receivable',
    category: 'piutang usaha',
    number: '10502',
    name: 'piutang usaha',
    subledger: 'customer',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'account receivable of management',
    category: 'piutang direksi',
    number: '10503',
    name: 'piutang direksi',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'account receivable of employee',
    category: 'piutang karyawan',
    number: '10504',
    name: 'piutang karyawan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other account receivable',
    category: 'piutang lainnya',
    number: '10599',
    name: 'piutang lainnya',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'down payment for purchase',
    category: 'uang muka pembelian',
    number: '10601',
    name: 'uang muka pembelian',
    subledger: 'supplier',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'down payment for purchase',
    category: 'uang muka pembelian',
    number: '10602',
    name: 'uang muka pembelian aset tetap',
    subledger: 'supplier',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'down payment for purchase',
    category: 'uang muka pembelian',
    number: '10603',
    name: 'uang muka pembayaran ekspedisi',
    subledger: 'expedition',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'income tax receivable',
    category: 'ppn masukan',
    number: '10701',
    name: 'ppn masukan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other current asset',
    category: 'aset lancar lainnya',
    number: '10801',
    name: 'surat berharga',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other current asset',
    category: 'aset lancar lainnya',
    number: '10901',
    name: 'iklan dibayar dimuka',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other current asset',
    category: 'aset lancar lainnya',
    number: '10902',
    name: 'sewa dibayar dimuka',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'other current asset',
    category: 'aset lancar lainnya',
    number: '10903',
    name: 'asuransi dibayar dimuka',
    subledger: '',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11101',
    name: 'tanah',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11202',
    name: 'bangunan pabrik',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11203',
    name: 'akumulasi penyusutan bangunan pabrik',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11301',
    name: 'bangunan kantor',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11302',
    name: 'akumulasi penyusutan bangunan kantor',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11401',
    name: 'mesin pabrik',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11402',
    name: 'akumulasi penyusutan mesin pabrik',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11501',
    name: 'peralatan kantor',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11502',
    name: 'akumulasi penyusutan peralatan kantor',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11601',
    name: 'kendaraan pabrik',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11602',
    name: 'akumulasi penyusutan kendaraan pabrik',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11701',
    name: 'kendaraan kantor',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11702',
    name: 'akumulasi penyusutan kendaraan kantor',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset',
    category: 'aset tetap',
    number: '11801',
    name: 'aset tidak berwujud',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'asset',
    type: 'aset',
    category_code: 'fixed asset depreciation',
    category: 'depresiasi aset tetap',
    number: '11802',
    name: 'akumulasi amortisasi aset tidak berwujud',
    subledger: 'fixed asset',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'note payable',
    category: 'wesel bayar',
    number: '20101',
    name: 'wesel bayar',
    subledger: '',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'account payable',
    category: 'hutang usaha',
    number: '20201',
    name: 'hutang usaha',
    subledger: 'supplier',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'down payment for sales',
    category: 'uang muka penjualan',
    number: '20301',
    name: 'uang muka penjualan',
    subledger: 'customer',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'down payment for sales',
    category: 'uang muka penjualan',
    number: '20302',
    name: 'uang muka penjualan aset tetap',
    subledger: 'customer',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'income tax payable',
    category: 'ppn keluaran',
    number: '20401',
    name: 'ppn keluaran',
    subledger: '',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'other current liability',
    category: 'kewajiban lainnya',
    number: '20501',
    name: 'hutang ekspedisi',
    subledger: 'expedition',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'other current liability',
    category: 'kewajiban lainnya',
    number: '20999',
    name: 'kewajiban jangka pendek lainnya',
    subledger: '',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'long term liability',
    category: 'kewajiban jangka panjang',
    number: '21101',
    name: 'hutang bank',
    subledger: '',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'long term liability',
    category: 'kewajiban jangka panjang',
    number: '21201',
    name: 'hipotik',
    subledger: '',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'long term liability',
    category: 'kewajiban jangka panjang',
    number: '21301',
    name: 'obligasi',
    subledger: '',
    group: '',
  },
  {
    type_code: 'liability',
    type: 'kewajiban',
    category_code: 'long term liability',
    category: 'kewajiban jangka panjang',
    number: '21999',
    name: 'kewajiban jangka panjang lainnya',
    subledger: '',
    group: '',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'owner equity',
    category: 'modal pemilik',
    number: '30101',
    name: 'stock capital',
    subledger: '',
    group: '',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'dividend',
    category: 'dividen',
    number: '30102',
    name: 'dividen',
    subledger: '',
    group: '',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'retained earning',
    category: 'laba ditahan',
    number: '30103',
    name: 'laba ditahan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'net income',
    category: 'laba bersih',
    number: '30111',
    name: 'laba rugi bulan berjalan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'modal',
    type: 'equity',
    category_code: 'net income',
    category: 'laba bersih',
    number: '30112',
    name: 'laba rugi tahun berjalan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'operational revenue',
    category: 'pendapatan operasional',
    number: '40101',
    name: 'penjualan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'operational revenue',
    category: 'pendapatan operasional',
    number: '40102',
    name: 'retur penjualan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'operational revenue',
    category: 'pendapatan operasional',
    number: '40103',
    name: 'potongan penjualan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'operational revenue',
    category: 'pendapatan operasional',
    number: '40999',
    name: 'pendapatan operasional lainnya',
    subledger: '',
    group: '',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'non operational revenue',
    category: 'pendapatan non operasional',
    number: '41101',
    name: 'pendapatan bunga',
    subledger: '',
    group: '',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'non operational revenue',
    category: 'pendapatan non operasional',
    number: '41102',
    name: 'pendapatan selisih kurs',
    subledger: '',
    group: '',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'non operational revenue',
    category: 'pendapatan non operasional',
    number: '41103',
    name: 'pendapatan selisih pembayaran',
    subledger: '',
    group: '',
  },
  {
    type_code: 'income',
    type: 'pendapatan',
    category_code: 'non operational revenue',
    category: 'pendapatan non operasional',
    number: '41999',
    name: 'pendapatan non operasional lainnya',
    subledger: '',
    group: '',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'cost of sales',
    category: 'beban pokok penjualan',
    number: '50101',
    name: 'beban pokok penjualan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'cost of sales',
    category: 'beban pokok penjualan',
    number: '50102',
    name: 'potongan pembelian',
    subledger: '',
    group: '',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'cost of sales',
    category: 'beban pokok penjualan',
    number: '50103',
    name: 'biaya retur',
    subledger: '',
    group: '',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'cost of sales',
    category: 'beban pokok penjualan',
    number: '50104',
    name: 'selisih sediaan',
    subledger: '',
    group: '',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52101',
    name: 'gaji tenaga kerja langsung',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52102',
    name: 'gaji tenaga kerja tidak langsung',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52103',
    name: 'listrik pabrik',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52104',
    name: 'air pabrik',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52105',
    name: 'konsumsi pabrik',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52106',
    name: 'biaya perawatan mesin',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52107',
    name: 'biaya akumulasi penyusutan bangunan pabrik',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52108',
    name: 'biaya akumulasi penyusutan kendaraan pabrik',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52109',
    name: 'biaya akumulasi penyusutan mesin pabrik',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'factory overhead',
    category: 'biaya overhead pabrik',
    number: '52999',
    name: 'biaya lainnya',
    subledger: '',
    group: 'pabrik',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53101',
    name: 'gaji karyawan kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53102',
    name: 'pendidikan dan pelatihan kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53103',
    name: 'konsumsi kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53104',
    name: 'transportasi kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53105',
    name: 'biaya perawatan kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53106',
    name: 'biaya sewa kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53107',
    name: 'biaya telepon kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53108',
    name: 'biaya asuransi kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53109',
    name: 'biaya internet kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53110',
    name: 'biaya peralatan kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53111',
    name: 'biaya konsultasi kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53112',
    name: 'biaya administrasi kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53113',
    name: 'biaya akumulasi penyusutan bangunan kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53114',
    name: 'biaya akumulasi penyusutan kendaraan kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53115',
    name: 'biaya akumulasi penyusutan peralatan kantor',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '53999',
    name: 'beban operasional kantor lainnya',
    subledger: '',
    group: 'kantor',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '54101',
    name: 'biaya entertainment',
    subledger: '',
    group: 'marketing',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '54102',
    name: 'biaya iklan',
    subledger: '',
    group: 'marketing',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'direct expense',
    category: 'beban operasional',
    number: '54999',
    name: 'beban operasional marketing lainnya',
    subledger: '',
    group: 'marketing',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'non operational expense',
    category: 'beban non operasional',
    number: '55101',
    name: 'beban bunga',
    subledger: '',
    group: '',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'non operational expense',
    category: 'beban non operasional',
    number: '55102',
    name: 'beban selisih kurs',
    subledger: '',
    group: '',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'non operational expense',
    category: 'beban non operasional',
    number: '55103',
    name: 'beban selisih pembayaran',
    subledger: '',
    group: '',
  },
  {
    type_code: 'expense',
    type: 'beban',
    category_code: 'non operational expense',
    category: 'beban non operasional',
    number: '55999',
    name: 'beban non operasional lainnya',
    subledger: '',
    group: '',
  },
]
